# Generated by Django 4.1.7 on 2023-02-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_slug_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Old', 'Old'), ('UpComing', 'UpComing')], max_length=100),
        ),
        migrations.AlterModelTable(
            name='product',
            table='app_Product',
        ),
    ]
