# Generated by Django 4.1.7 on 2023-02-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review_text',
            field=models.TextField(max_length=300),
        ),
    ]
