# Generated by Django 4.1.7 on 2023-02-23 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_productreview_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 23, 13, 6, 53, 272462)),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_rating',
            field=models.IntegerField(default=0),
        ),
    ]
