# Generated by Django 4.1.7 on 2023-02-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_productreview_created_at_productreview_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
