# Generated by Django 4.1.7 on 2023-03-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_productreview_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
