# Generated by Django 4.1.7 on 2023-03-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_orderitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Order Processing', 'Order Processing'), ('On the Way', 'On the Way'), ('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled')], default='Pending', max_length=50),
        ),
    ]
