# Generated by Django 4.1.7 on 2023-03-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
    ]
